// /** @type {import('tailwindcss').Config} */
// export default {
//   content: [
//     './pages/**/*.{ts,tsx}',
//     './components/**/*.{ts,tsx}',
//     './app/**/*.{ts,tsx}',
//     './src/**/*.{ts,tsx}',
//   ],
//   darkMode: ['selector', '[data-theme="dark"]'],
//   plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
//   prefix: '',
//   safelist: [
//     'lg:col-span-4',
//     'lg:col-span-6',
//     'lg:col-span-8',
//     'lg:col-span-12',
//     'border-border',
//     'bg-card',
//     'border-error',
//     'bg-error/30',
//     'border-success',
//     'bg-success/30',
//     'border-warning',
//     'bg-warning/30',
//   ],
//   theme: {
//     container: {
//       center: true,
//       padding: {
//         '2xl': '2rem',
//         DEFAULT: '1rem',
//         lg: '2rem',
//         md: '2rem',
//         sm: '1rem',
//         xl: '2rem',
//       },
//       screens: {
//         '2xl': '86rem',
//         lg: '64rem',
//         md: '48rem',
//         sm: '40rem',
//         xl: '80rem',
//       },
//     },
//     extend: {
//       colors: {},
//       animation: {
//         float: 'float 10s ease-in-out infinite',
//       },
//       keyframes: {
//         float: {
//           '0%': { transform: 'translateY(0)' },
//           '50%': { transform: 'translateY(-10px)' },
//           '100%': { transform: 'translateY(0)' },
//         },
//       },
//       animation: {
//         'accordion-down': 'accordion-down 0.2s ease-out',
//         'accordion-up': 'accordion-up 0.2s ease-out',
//       },
//       borderRadius: {
//         lg: 'var(--radius)',
//         md: 'calc(var(--radius) - 2px)',
//         sm: 'calc(var(--radius) - 4px)',
//       },
//       colors: {
//         border: 'hsl(var(--border))',
//         card: {
//           DEFAULT: 'hsl(var(--card))',
//           foreground: 'hsl(var(--card-foreground))',
//         },
//         destructive: {
//           DEFAULT: 'hsl(var(--destructive))',
//           foreground: 'hsl(var(--destructive-foreground))',
//         },
//         input: 'hsl(var(--input))',
//         muted: {
//           DEFAULT: 'hsl(var(--muted))',
//           foreground: 'hsl(var(--muted-foreground))',
//         },
//         primary: {},
//         primary: {
//           DEFAULT: 'hsl(var(--primary))',
//           foreground: 'hsl(var(--primary-foreground))',
//         },
//         ring: 'hsl(var(--ring))',
//         secondary: {
//           DEFAULT: 'hsl(var(--secondary))',
//           foreground: 'hsl(var(--secondary-foreground))',
//         },
//         success: 'hsl(var(--success))',
//         error: 'hsl(var(--error))',
//         warning: 'hsl(var(--warning))',
//         background: 'var(--background)',
//         foreground: 'var(--foreground)',
//         jaffa: {
//           50: '#fef6ee',
//           100: '#feead6',
//           200: '#fbd2ad',
//           300: '#f9b278',
//           400: '#f5853f',
//           500: '#f2661d',
//           600: '#e34c13',
//           700: '#bc3812',
//           800: '#962e16',
//           900: '#792815',
//           950: '#411109',
//         },
//         astral: {
//           50: '#f0f9fb',
//           100: '#d8eef5',
//           200: '#b6deeb',
//           300: '#83c4dd',
//           400: '#4aa3c6',
//           500: '#2e86ab',
//           600: '#296d91',
//           700: '#275a77',
//           800: '#284b62',
//           900: '#254054',
//           950: '#142938',
//         },
//         shark: {
//           50: '#f8f7f7',
//           100: '#f0eeee',
//           200: '#dddada',
//           300: '#bfbaba',
//           400: '#9b9595',
//           500: '#7f7879',
//           600: '#686162',
//           700: '#554f4f',
//           800: '#484445',
//           900: '#3f3b3b',
//           950: '#252323',
//         },
//         white: '#FBFFFE',
//       },
//       fontFamily: {
//         mono: ['var(--font-geist-mono)'],
//         sans: ['var(--font-geist-sans)'],
//       },
//       keyframes: {
//         'accordion-down': {
//           from: { height: '0' },
//           to: { height: 'var(--radix-accordion-content-height)' },
//         },
//         'accordion-up': {
//           from: { height: 'var(--radix-accordion-content-height)' },
//           to: { height: '0' },
//         },
//       },
//       typography: ({ theme }) => ({
//         DEFAULT: {
//           css: {
//             '--tw-prose-body': 'var(--text)',
//             '--tw-prose-headings': 'var(--text)',
//             h1: {
//               fontSize: '4rem',
//               fontWeight: 'normal',
//               marginBottom: '0.25em',
//             },
//           },
//         },
//       }),
//     },
//   },
// }
